spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autumn?characterEncoding=utf8&allowMultiQueries=true
    username: ghimmk
    password: 5857
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: ac.linker.mapper
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8081

logging:
  pattern:
    console: "%clr(%date{'HH:mm:ss'}){faint} %clr(-%5level) %clr([%thread]){faint} %clr(%logger.%method:%line){cyan} %clr(:){faint} %m%n%wEx"
    file: "%clr(%date{'yyyy-MM-dd HH:mm:ss'}){faint} %clr(-%5level) %clr([%thread]){faint} %clr(%logger.%method:%line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.tester"

  file:
    name: /var/log/summer_mvc/summer.tester
    max-history: 20
    max-size: 1MB
